import React from "react";

export default function PrivacyPolicyPage() {
  return (
    <section className="container mx-auto px-4 py-12 max-w-4xl">
      <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
      <p className="text-muted-foreground mb-8">Last updated: April 19, 2022</p>

      <div className="prose prose-lg max-w-none space-y-6">
        <p>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">Interpretation and Definitions</h2>

        <h3 className="text-xl font-semibold mt-6 mb-3">Interpretation</h3>
        <p>
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-3">Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;Organization&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Sydney Bethel Marthoma Church, 13 Crown Street Harris Park.</li>
          <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li><strong>Country</strong> refers to: New South Wales, Australia</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
          <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Organization. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Organization in analyzing how the Service is used.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li><strong>Website</strong> refers to Sydney Bethel Marthoma Church, accessible from <a href="https://sydneymarthoma.church" className="text-primary underline">https://sydneymarthoma.church</a></li>
          <li><strong>You</strong> means the individual accessing or using the Service, or the Organization, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h2 className="text-2xl font-bold mt-8 mb-4">Collecting and Using Your Personal Data</h2>

        <h3 className="text-xl font-semibold mt-6 mb-3">Types of Data Collected</h3>

        <h4 className="text-lg font-semibold mt-4 mb-2">What personal data we collect and what we do with it</h4>
        <p>
          At BMTC Sydney we collect personal information using paper forms and emails. We only collect personal information that is necessary for the activities and ministries of our church, and we use it for communication, pastoral care, administration and statistics. Personal information is not distributed to any organization outside of our church, without consent of the individual. Personal information on paper is stored securely and is disposed of in a secure and sensitive way when no longer needed. Personal information is also stored in a church management software database which is available on a desktop computer. Access to this computer is restricted.
        </p>
        <p>
          We also store personal information in our church directory which is hosted by instantchurchdirectory.com. Church members are only included in the directory if they have given their permission. Such persons can access and edit their own and their family&apos;s information by logging in with a username and password. Privacy policy for the church directory is available at <a href="https://www.instantchurchdirectory.com/privacypolicy" className="text-primary underline" target="_blank" rel="noopener noreferrer">https://www.instantchurchdirectory.com/privacypolicy</a>.
        </p>

        <h4 className="text-lg font-semibold mt-4 mb-2">Personal Data</h4>
        <p>
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Email address - When sending bulk emails (e.g. church notices, newsletters) to multiple recipients, addresses will be placed in the BCC (blind carbon copy) field to hide the email addresses.</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="text-lg font-semibold mt-4 mb-2">Usage Data</h4>
        <p>
          Usage Data is collected automatically when using the Service.
        </p>
        <p>
          Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>
        <p>
          When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
        </p>
        <p>
          IP addresses might be collected and used to monitor, block unauthorized access to this site.
        </p>

        <h4 className="text-lg font-semibold mt-4 mb-2">Tracking Technologies and Cookies</h4>
        <p>
          Our website does not currently use cookies, therefore, we collect no information via cookies when you visit our website.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-3">Use of Your Personal Data</h3>
        <p>The Organization may use Personal Data for the following purposes:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
          <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
          <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
          <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
          <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, and your experience.</li>
        </ul>

        <p className="mt-4">We may share Your personal information in the following situations:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
          <li><strong>With Affiliates:</strong> We don&apos;t share Your information with Our affiliates.</li>
          <li><strong>With Your consent:</strong> We don&apos;t disclose Your personal information for any other purpose without Your consent.</li>
        </ul>

        <h3 className="text-xl font-semibold mt-6 mb-3">Retention of Your Personal Data</h3>
        <p>
          The Organization will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
        </p>
        <p>
          The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-3">Transfer of Your Personal Data</h3>
        <p>
          BMTC Sydney will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-3">Disclosure of Your Personal Data</h3>

        <h4 className="text-lg font-semibold mt-4 mb-2">Law enforcement</h4>
        <p>
          Under certain circumstances, the Organization may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
        </p>

        <h4 className="text-lg font-semibold mt-4 mb-2">Other legal requirements</h4>
        <p>The Organization may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Organization</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>Protect the personal safety of Users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>

        <h3 className="text-xl font-semibold mt-6 mb-3">Security of Your Personal Data</h3>
        <p>
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-3">Children&apos;s Privacy</h3>
        <p>
          Our site might use children&apos;s photos in group or a group photo of an event. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to contact back. Our Sunday school has put forth the parent&apos;s consent while submitting the registration form. For queries please contact Sunday school headmaster.
        </p>
        <p>
          If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&apos;s consent before We collect and use that information.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-3">Links to Other Websites</h3>
        <p>
          Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
        </p>
        <p>
          Articles on this site may include embedded content (e.g. videos, images, articles, etc.). Embedded content from other websites behaves in the exact same way as if the visitor has visited the other website.
        </p>
        <p>
          These websites may collect data about you, use cookies, embed additional third-party tracking, and monitor your interaction with that embedded content, including tracking your interaction with the embedded content if you have an account and are logged in to that website.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-3">Changes to this Privacy Policy</h3>
        <p>
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
        </p>
        <p>
          We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-3">Contact Us</h3>
        <p>
          If you have any questions about this Privacy Policy, You can contact us:
        </p>
        <p>
          By visiting this page on our website: <a href="/contact-us" className="text-primary underline">https://sydneymarthoma.church/contact-us/</a>
        </p>
      </div>
    </section>
  );
}
